// src-web/components/AppHeader.tsx
import React, { useEffect, useState } from 'react';
import { AIModel, Conversation, event } from "../models/Model";
import store from '../store';
import { firstElement, lastElement } from '../utils';

interface AppHeaderProps {
    modelId: string;
    conversationId: string;
    onModelChange: (model: string) => void;
    onConversationChange: (id: string) => void;
}

const AppHeader: React.FC<AppHeaderProps> = ({
    modelId,
    conversationId,
    onModelChange,
    onConversationChange,
}) => {

    const [models, setModels] = useState<AIModel[]>([]);
    const [conversations, setConversations] = useState<Conversation[]>([]);

    // 更新模型列表
    const handleModels = (models: AIModel[]) => {
        const sortedModels = [...models].sort((a, b) => a.name.localeCompare(b.name));
        setModels(sortedModels);
        if (!modelId) {
            onModelChange(firstElement(sortedModels).model)
        }
    };

    const handleWindowMessage = (e: MessageEvent) => {
        const { type, data, text } = e.data;
        switch (type) {
            case 'tags-end':
                handleModels(text.models as AIModel[]);
                break;
        }
    };

    useEffect(() => {
        window.addEventListener('message', handleWindowMessage);
        return () => window.removeEventListener('message', handleWindowMessage);
    }, [])

    const getModels = () => {
        event.getModels();
    }

    const getConversations = async () => {
        const conversations = await store.getConversations();
        setConversations([...conversations]);
        if (!conversationId && firstElement(conversations).id) {
            onConversationChange(firstElement(conversations).id)
        }
        return conversations;
    }

    useEffect(() => {
        getModels();
        getConversations();
    }, [])

    

    const onCreateConversation = async () => {
        await store.createConversation();
        const conversations = await getConversations();
        onConversationChange(lastElement(conversations).id)
    }

    const onDeleteConversation = async () => {
        await store.deleteConversation(conversationId);
        await store.removeMessagesById(conversationId);
        const conversations = await getConversations();
        onConversationChange(firstElement(conversations).id)
    }

    const onClearConversation = async () => {
        await store.setMessagesById(conversationId, []);
        onConversationChange(conversationId);
    }

    return (
        <div className="history-area">
            <select
                className="vscode-select"
                id="model-select"
                value={modelId}
                onChange={(e) => onModelChange(e.target.value)}
            >
                {models.map(model => (
                    <option key={model.name} value={model.name}>
                        {model.name}
                    </option>
                ))}
            </select>

            <select
                className="vscode-select"
                id="history-select"
                value={conversationId}
                onChange={(e) => onConversationChange(e.target.value)}
            >
                {conversations.map(conv => (
                    <option key={conv.id} value={conv.id}>
                        {conv.title}
                    </option>
                ))}
            </select>

            <button
                className="vscode-button-small"
                id="create-button"
                onClick={onCreateConversation}
            >
                +
            </button>

            <button
                className="vscode-button-small"
                id="delete-button"
                onClick={onDeleteConversation}
            >
                -
            </button>

            <button
                className="vscode-button-small"
                id="clear-button"
                title="清空消息"
                onClick={onClearConversation}
            >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M6 7V18C6 19.1046 6.89543 20 8 20H16C17.1046 20 18 19.1046 18 18V7M4 7H20M10 11V16M14 11V16M15 7V4C15 3.44772 14.5523 3 14 3H10C9.44772 3 9 3.44772 9 4V7"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
            </button>
        </div>
    );
};

export default AppHeader;

// src-web/src/components/AppHeader.vue
<template>
  <div class="header-area">
    <el-select style="max-width: 300px" class="el-select--vscode" :model-value="conversationId"
      @change="onConversationChange">
      <el-option v-for="option in conversations" :key="option.id" :value="option.id" :label="option.title">
      </el-option>
    </el-select>
    <el-button class="vscode-button-small" id="create-button" title="配置模型" icon="Setting" @click="openDialog">
    </el-button>
    <el-button class="vscode-button-small" id="create-button" title="新增会话" icon="Plus" @click="onCreateConversation">
    </el-button>
    <el-button class="vscode-button-small" id="delete-button" title="删除会话" icon="Minus" @click="onDeleteConversation">
    </el-button>
    <el-button class="vscode-button-small" id="clear-button" title="清空消息" icon="Delete" @click="onClearConversation">
    </el-button>
  </div>
  <SettingDialog v-if="dialogVisible" :vendor-id="vendorId" :model-id="modelId" @cancel="onDialogCancel"
    @submit="onDialogSubmit"></SettingDialog>
</template>

<script setup lang="ts">
import { chatService, type ChatVendor } from "@/api";
import { ChatConversation } from "@/models/Model";
import store from "@/store";
import { firstElement, lastElement } from "@/utils";
import { onMounted, ref } from "vue";
import SettingDialog from "./AppSettingDialog.vue";

const props = defineProps({
  vendorId: {
    default: "",
  },
  modelId: {
    default: "",
  },
  conversationId: {
    default: "",
  },
});

const emit = defineEmits<{
  (e: "update:vendorId", value: ChatVendor): void;
  (e: "update:modelId", value: string): void;
  (e: "update:conversationId", value: string): void;
}>();

const conversations = ref<ChatConversation[]>([]);
const getConversations = async () => {
  const convs = await store.getConversations();
  conversations.value = [...convs];
  if (!props.conversationId && firstElement(convs).id) {
    emit("update:conversationId", firstElement(convs).id);
  }
  return convs;
};

const onConversationChange = (id: string) => {
  emit("update:conversationId", id);
};

// 按钮操作
const onCreateConversation = async () => {
  await store.createConversation();
  const convs = await getConversations();
  emit("update:conversationId", lastElement(convs).id);
};

const onDeleteConversation = async () => {
  await store.deleteConversation(props.conversationId);
  await store.removeMessagesById(props.conversationId);
  const convs = await getConversations();
  emit("update:conversationId", firstElement(convs).id);
};

const onClearConversation = async () => {
  await store.setMessagesById(props.conversationId, []);
  emit("update:conversationId", props.conversationId);
};

const dialogVisible = ref(false);

const openDialog = () => {
  dialogVisible.value = true;
};

const onDialogCancel = () => {
  dialogVisible.value = false;
  if (props.vendorId) {
    chatService.setVendor(props.vendorId as ChatVendor);
  }
};

const onDialogSubmit = ({ vendorId, modelId }) => {
  dialogVisible.value = false;
  chatService.setVendor(vendorId);
  emit("update:vendorId", vendorId);
  emit("update:modelId", modelId);
};

onMounted(() => {
  getConversations();
});
</script>
