// src-web/src/App.vue
<template>
  <div class="chat-container">
    <AppHeader :vendorId="vendorId" :modelId="modelId" :conversationId="conversationId"
      @update:vendorId="handleVendorChange" @update:modelId="handleModelChange"
      @update:conversationId="handleConversationChange" />
    <AppBody :messages="messages" :latestMessage="latestMessage" :loading="loading" />
    <AppFooter v-model="prompt" :loading="loading" @click="onButtonClick" />
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, unref } from "vue";
import { chatService, type ChatVendor } from "./api";
import AppBody from "./components/AppBody.vue";
import AppFooter from "./components/AppFooter.vue";
import AppHeader from "./components/AppHeader.vue";
import { ChatMessage } from "./models/Model";
import store from "./store/index";

const KEY_VENDOR = "code-assist.vendor";
const KEY_MODEL = "code-assist.model";
const KEY_CONV = "code-assist.conversation";


const vendorId = ref(localStorage.getItem(KEY_VENDOR) as ChatVendor);
const modelId = ref(localStorage.getItem(KEY_MODEL) || "");
const conversationId = ref(localStorage.getItem(KEY_CONV) || "");

chatService.setVendor(vendorId.value);

const latestMessage = ref(new ChatMessage("assistant"));
const messages = ref<ChatMessage[]>([]);
const loading = ref(false);
const prompt = ref("");

// 加载消息
const loadMessages = async () => {
  const loadedMessages = await store.getMessagesById(conversationId.value);
  messages.value = loadedMessages;
};

// 处理窗口消息
const handleWindowMessage = (e: MessageEvent) => {
  const { type, text } = e.data;
  switch (type) {
    case "optimization":
      handleOptimization(text);
      break;
    case "explanation":
      handleExplanation(text);
      break;
  }
};

// 等待 AI 回复
const handleChatRequest = async (
  modelId: string,
  content: string,
  messages: ChatMessage[]
) => {
  loading.value = true;
  try {
    latestMessage.value.content = "...";
    await chatService.chat(
      {
        model: modelId,
        content: content,
        messages: messages,
      },
      (delta: string) => {
        handleChating(delta)
      },
      () => {
        loading.value = false;
        handleChatEnd();      
      }
    );
  } catch (error: any) {
    loading.value = false;
    handleChatEnd();
  }
};

const handleChating = (delta: string) => {
  if (latestMessage.value.content === "...") {
    latestMessage.value.content = "";
  }

  latestMessage.value.content += delta;
}
// AI 结束回答
const handleChatEnd = () => {
  const message = new ChatMessage("assistant");
  message.content = latestMessage.value.content;
  messages.value = [...messages.value, message];
  store.setMessagesById(conversationId.value, unref(messages));
};

const handleOptimization = (code: string) => {
  if (!code) return;
  prompt.value = `优化一下这段代码
\`\`\`
${code}
\`\`\``;
  onButtonClick();
};

const handleExplanation = (code: string) => {
  if (!code) return;
  prompt.value = `解释一下这段代码
\`\`\`
${code}
\`\`\``;
  onButtonClick();
};

// 发送消息
const onButtonClick = async () => {
  const content = prompt.value;
  if (loading.value) {
    chatService.stop();
    return;
  }
  if (!modelId.value) {
    return;
  }
  if (!prompt.value.trim()) {
    return;
  }
  prompt.value = "";
  await store.updateConversationTitle(conversationId.value, content);
  const message = new ChatMessage("user");
  message.content = content;
  messages.value = [...messages.value, message];
  store.setMessagesById(conversationId.value, unref(messages));
  handleChatRequest(modelId.value, content, messages.value);
};

const handleVendorChange = (vendor: ChatVendor) => {
  localStorage.setItem(KEY_VENDOR, vendor);
  vendorId.value = vendor;
};

// 模型变更处理
const handleModelChange = (id: string) => {
  localStorage.setItem(KEY_MODEL, id);
  modelId.value = id;
};

// 会话变更处理
const handleConversationChange = (id: string) => {
  localStorage.setItem(KEY_CONV, id);
  conversationId.value = id;
  messages.value = [];
  loadMessages();
};

onMounted(() => {
  window.addEventListener("message", handleWindowMessage);
  loadMessages();
});

onUnmounted(() => {
  window.removeEventListener("message", handleWindowMessage);
});
</script>

// src-web/App.tsx
import React, { useEffect, useState } from 'react';
import AppBody from './components/AppBody';
import AppFooter from './components/AppFooter';
import AppHeader from './components/AppHeader';
import { ChatMessage, event } from "./models/Model";
import store from './store/index';

const modelIdL = localStorage.getItem('modelId') || '';
const conversationIdL = localStorage.getItem('conversationId') || '';

const ChatComponent: React.FC = () => {

    const [modelId, setModelId] = useState(modelIdL)
    const [conversationId, setConversationId] = useState(conversationIdL)

    console.log('[Webview]', conversationId);

    const [tempMessage, setTempMessage] = useState(new ChatMessage('assistant'));
    const [isLoading, setLoading] = useState<boolean>(false);
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [inputValue, setInputValue] = useState('');

    useEffect(() => {
        window.addEventListener('message', handleWindowMessage);
        return () => window.removeEventListener('message', handleWindowMessage);
    }, []);

    useEffect(() => {
        loadMessages();
    }, [conversationId])

    const loadMessages = async () => {
        const loadedMessages = await store.getMessagesById(conversationId);
        setMessages([...loadedMessages]);
    };

    // 接收插件进程消息
    const handleWindowMessage = (e: MessageEvent) => {
        const { type, text } = e.data;
        switch (type) {
            case 'chat-pre':
                handleChatRequest();
                break;
            case 'chat-start':
                handleChatStart();
                break;
            case 'chat-data':
                handleChatData(text);
                break;
            case 'chat-end':
                handleChatEnd();
                break;
            case 'optimization':
                handleOptimization(text);
                break;
            case 'explanation':
                handleExplanation(text);
                break;
        }
    };

    // 等待 AI 回复
    const handleChatRequest = () => {
        setLoading(true);
        setTempMessage(prev => {
            return {
                ...prev,
                content: '...',
            }
        })
    };
    // AI 开始回答
    const handleChatStart = () => {
        setTempMessage(prev => {
            return {
                ...prev,
                content: '',
            }
        })
    };

    // AI 回答中
    const handleChatData = (text: string) => {
        setTempMessage(prev => {
            const json = JSON.parse(text);
            const delta = json.message.content;
            return {
                ...prev,
                content: prev.content + delta
            }
        });
    };

    // AI 结束回答
    const handleChatEnd = () => {
        setLoading(false);
        setTempMessage(temp => {
            setMessages(prev => {
                const message = new ChatMessage('assistant');
                message.content = temp.content;
                const next = [...prev, message];
                setConversationId(id => {
                    store.setMessagesById(id, next)
                    return id;
                })
                return next;
            });
            return temp;
        })

    };

    const handleOptimization = (code: string) => {
        if (!code) return;
        setInputValue(`优化一下这段代码\`\`\`${code}\`\`\``);
        onButtonClick();
    };

    const handleExplanation = (code: string) => {
        if (!code) return;
        setInputValue(`解释一下这段代码\`\`\`${code}\`\`\``);
        onButtonClick();
    };
    // 发送消息
    const onButtonClick = async () => {
        if (!inputValue.trim()) {
            return;
        }
        if (isLoading) {
            event.stop();
            return;
        }
        await store.updateConversationTitle(conversationId, inputValue);
        setInputValue('');
        setMessages(prev => {
            const message = new ChatMessage('user');
            message.content = inputValue;
            const next = [...prev, message]
            event.chat(modelId, inputValue, next);
            store.setMessagesById(conversationId, next)
            return next;
        });
    };

    return (
        <div className="chat-container">
            <AppHeader
                modelId={modelId}
                conversationId={conversationId}
                onModelChange={(id: string) => {
                    localStorage.setItem('code-assist.modelId', id);
                    setModelId(id);
                }}
                onConversationChange={(id: string) => {
                    localStorage.setItem('code-assist.conversationId', id);
                    setMessages([]);
                    setConversationId(id);
                }}
            />
            <AppBody messages={messages} tempMessage={tempMessage} isLoading={isLoading} />
            <AppFooter
                inputValue={inputValue}
                isLoading={isLoading}
                onInputChange={setInputValue}
                onButtonClick={onButtonClick}
            />
        </div>
    );
};

export default ChatComponent;
